import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const pages={
  'musees':['paris','lyon','marseille','toulouse','bordeaux','lille','nantes','strasbourg','montpellier','grenoble','angers','saint-etienne','troyes','saint-malo','chambery'],
  'regions':['ile-de-france','auvergne-rhone-alpes','hauts-de-france','occitanie','nouvelle-aquitaine','bretagne','normandie','grand-est','bourgogne-franche-comte','centre-val-de-loire','pays-de-la-loire','provence-alpes-cote-d-azur','corse'],
  'departements':['nord','rhone','gironde','seine-maritime','hauts-de-seine'],
  'themes':['musees-beaux-arts','musees-art-moderne-contemporain','musees-histoire','musees-sciences','musees-histoire-naturelle','musees-archeologie','musees-arts-decoratifs','musees-automobile','musees-mode','musees-insolites'],
  'visiter':['musees-gratuits','musees-en-famille','musees-avec-enfants','musees-accessibles','visites-guidees','musees-ouverts-le-dimanche','musees-ouverts-le-lundi'],
  'expositions':['paris','lyon','marseille'],
  'inspiration':['meilleurs-musees-france','musees-insolites-france','musees-a-faire-en-famille','week-end-culturel','musees-a-voir-une-fois'],
  'guides':['comment-preparer-visite-musee','combien-de-temps-pour-visiter-un-musee','musees-gratuits-premier-dimanche','pass-musees','visiter-musee-avec-enfant'],
  'musee':['louvre','orsay','fondation-louis-vuitton','musee-grevin','musee-confluences','louvre-lens','cernuschi','musee-de-l-homme','bourdelle','granet','fabre','musee-de-grenoble','christian-dior-granville','arts-decoratifs']
};
const labels={musees:'Musées',regions:'Régions',departements:'Départements',themes:'Thèmes',visiter:'Préparer une visite',expositions:'Expositions',inspiration:'Inspiration',guides:'Guides',musee:'Musée'};
const human=s=>s.replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase()).replace('D ','d’').replace('L ','l’');
const prefix=(level=0)=>level?'../'.repeat(level):'';
function shell({title,desc,body,level=0}){const p=prefix(level);return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${title} | Visite Musée</title><meta name="description" content="${desc}"><link rel="icon" href="${p}assets/logo.svg"><link rel="stylesheet" href="${p}assets/styles.css"></head><body><header class="site-header"><div class="wrap nav"><a class="brand" href="${p}"><img src="${p}assets/logo.svg" alt=""><span>VISITE<br>MUSÉE</span></a><button class="menu-button" data-menu-button aria-expanded="false" aria-label="Ouvrir le menu">☰</button><nav class="menu" data-menu><a href="${p}musees/">Musées</a><a href="${p}regions/">Destinations</a><a href="${p}themes/">Thèmes</a><a href="${p}expositions/">Expositions</a><a href="${p}visiter/musees-en-famille/">En famille</a><a href="${p}musees/#carte">Carte</a></nav></div></header><main>${body}</main>${footer(p)}<script src="${p}assets/app.js"></script></body></html>`}
function footer(p){return `<footer class="footer"><div class="wrap"><div class="footer-grid"><div class="brand">VISITE<br>MUSÉE</div><div><strong>Explorer</strong><a href="${p}musees/">Tous les musées</a><a href="${p}themes/">Par thème</a></div><div><strong>Sortir</strong><a href="${p}expositions/">Expositions</a><a href="${p}visiter/musees-gratuits/">Musées gratuits</a></div><div><strong>Comprendre</strong><a href="${p}guides/">Guides</a><a href="${p}inspiration/">Inspiration</a></div></div><div class="legal">Prototype structurel · Les données pratiques seront publiées uniquement après vérification auprès des sources officielles.</div></div></footer>`}
const home=`<section class="hero"><div class="wrap"><div class="eyebrow">Le moteur français des sorties culturelles</div><h1>Quel musée allez-vous découvrir <span class="accent">aujourd’hui&nbsp;?</span></h1><form class="search" action="musees/"><input aria-label="Rechercher" placeholder="Musée, ville, artiste ou thème…"><button>TROUVER UN MUSÉE →</button></form><div class="quick"><a class="chip" href="musees/paris/">Paris</a><a class="chip" href="themes/musees-art-moderne-contemporain/">Art contemporain</a><a class="chip" href="visiter/musees-avec-enfants/">Avec des enfants</a><a class="chip" href="visiter/musees-gratuits/">Gratuit</a><a class="chip" href="themes/musees-sciences/">Sciences</a><a class="chip" href="expositions/">Expositions</a></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Sélection éditoriale</div><h2>À voir en ce moment</h2></div><a href="expositions/">Toutes les expositions →</a></div><div class="poster-grid"><a class="poster blue" href="expositions/"><small>Programmation</small><div><div class="number">01</div><h3>Expositions à découvrir</h3><p>Données et dates à venir après validation.</p></div></a><a class="poster coral" href="musee/orsay/"><small>Musée</small><div><h3>Musée d’Orsay</h3><p>Art · Paris</p></div></a><a class="poster yellow" href="musee/musee-confluences/"><small>Musée</small><div><h3>Musée des Confluences</h3><p>Sciences · Lyon</p></div></a></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><h2>Où voulez-vous sortir&nbsp;?</h2></div><div class="cities">${pages.musees.slice(0,10).map(x=>`<a class="city" href="musees/${x}/">${human(x)}</a>`).join('')}</div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><h2>Explorer par envie</h2></div><div class="themes"><a class="theme" href="themes/musees-beaux-arts/">ART</a><a class="theme" href="themes/musees-histoire/">HISTOIRE</a><a class="theme" href="themes/musees-sciences/">SCIENCES</a><a class="theme" href="themes/musees-arts-decoratifs/">DESIGN</a><a class="theme" href="themes/musees-mode/">MODE</a><a class="theme" href="themes/musees-insolites/">INSOLITE</a></div></div></section>
<section class="section planner"><div class="wrap planner-grid"><div><div class="eyebrow">Je ne sais pas quoi choisir</div><h2>Inspirez-moi.</h2><p>Composez une sortie selon votre temps, votre compagnie et vos envies.</p></div><div><div class="choice-label">J’ai…</div><button class="filter" data-filter>1 heure</button><button class="filter" data-filter>Un après-midi</button><button class="filter" data-filter>Une journée</button><div class="choice-label">Je suis avec…</div><button class="filter" data-filter>Seul</button><button class="filter" data-filter>À deux</button><button class="filter" data-filter>Des enfants</button><div class="choice-label">J’aime…</div><button class="filter" data-filter>Art</button><button class="filter" data-filter>Histoire</button><button class="filter" data-filter>Sciences</button><br><button class="button" data-inspire>INSPIRER MA SORTIE →</button><div class="inspire-result" data-inspire-result hidden></div></div></div></section>`;
write('index.html',shell({title:'Trouvez un musée à visiter en France',desc:'Explorez les musées de France par ville, thème et conditions de visite.',body:home}));
function directory(){return `<section class="page-hero"><div class="wrap"><div class="eyebrow">Annuaire culturel</div><h1>Trouvez votre prochain <span class="accent">musée.</span></h1><p class="page-intro">Explorez par ville, collection et conditions de visite. Les données pratiques seront ajoutées après vérification.</p></div></section><section class="section"><div class="wrap directory"><aside class="filters"><h2>Filtres</h2>${['Région','Thème','Avec enfants','Gratuit','Accessible'].map(x=>`<div class="filter-group"><h3>${x}</h3><label><input type="checkbox"> Afficher les résultats</label></div>`).join('')}</aside><div data-results><div class="viewbar"><strong>Musées référencés</strong><div class="views"><button class="active" data-view="list">Liste</button><button data-view="map">Carte</button></div></div><div class="result-grid">${pages.musee.slice(0,6).map((x,i)=>`<a class="result-card" href="../musee/${x}/"><small>${i%2?'LYON · SCIENCES':'PARIS · ART'}</small><div><h3>${human(x)}</h3><p>Informations pratiques à vérifier</p></div></a>`).join('')}</div><div class="map-placeholder" id="carte">CARTE DE FRANCE<br><small>Données à connecter</small></div></div></div></section>`}
write('musees/index.html',shell({title:'Musées de France',desc:'Annuaire des musées de France.',body:directory(),level:1}));
function hub(type){const list=pages[type];return `<section class="page-hero"><div class="wrap"><div class="eyebrow">${labels[type]}</div><h1>Explorer par <span class="accent">${labels[type].toLowerCase()}.</span></h1><p class="page-intro">Une vue structurée de la future base Visite Musée.</p></div></section><section class="section"><div class="wrap"><div class="result-grid">${list.map(x=>`<a class="result-card" href="${x}/"><small>${labels[type]}</small><div><h3>${human(x)}</h3><p>Découvrir →</p></div></a>`).join('')}</div></div></section>`}
for(const type of Object.keys(pages))if(type!=='musees')write(`${type}/index.html`,shell({title:labels[type],desc:`Explorer ${labels[type].toLowerCase()}.`,body:hub(type),level:1}));
function landing(type,slug){const name=human(slug);return `<section class="page-hero"><div class="wrap"><div class="eyebrow">${labels[type]}</div><h1>${name}</h1><p class="page-intro">Cette page accueillera une sélection issue de la base de données, avec des critères transparents et des informations vérifiées.</p></div></section><section class="section"><div class="wrap"><div class="stats"><div class="stat"><strong>—</strong>musées vérifiés</div><div class="stat"><strong>—</strong>gratuits</div><div class="stat"><strong>—</strong>en famille</div><div class="stat"><strong>—</strong>accessibles</div></div></div></section><section class="section"><div class="wrap"><div class="section-head"><h2>À découvrir</h2></div><div class="result-grid"><div class="result-card"><small>SÉLECTION</small><h3>Contenu à connecter</h3></div><div class="result-card"><small>CARTE</small><h3>Vue géographique</h3></div></div></div></section>`}
function museum(slug){const name=human(slug);return `<section class="page-hero"><div class="wrap"><div class="eyebrow">Fiche musée · Informations à vérifier</div><h1>${name}</h1></div></section><section><div class="wrap museum-layout"><div class="visual">${name}</div><div class="facts">${[['Ville','À renseigner'],['Collections','À renseigner'],['Aujourd’hui','À vérifier'],['Durée conseillée','À vérifier'],['Tarif','À vérifier'],['Gratuité','À vérifier'],['Accessibilité','À vérifier'],['Dernière vérification','Non vérifié']].map(([a,b])=>`<div class="fact"><strong>${a}</strong><span class="placeholder">${b}</span></div>`).join('')}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><h2>Pourquoi ce musée&nbsp;?</h2></div><div class="three-reasons">${['Pour ses collections','Pour son architecture','Pour sa programmation'].map((x,i)=>`<div class="reason"><span>0${i+1}</span><h3>${x}</h3><p class="placeholder">Argument éditorial à documenter.</p></div>`).join('')}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><h2>Préparer la visite</h2></div><p class="page-intro">Horaires, tarifs, réservation, accès, services et conditions famille seront intégrés depuis des sources officielles avec une date de vérification.</p></div></section>`}
for(const [type,list] of Object.entries(pages))for(const slug of list)write(`${type}/${slug}/index.html`,shell({title:human(slug),desc:`Découvrez ${human(slug)} sur Visite Musée.`,body:type==='musee'?museum(slug):landing(type,slug),level:2}));
function write(file,content){const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content)}
console.log(`${countHtml(root)} pages générées.`);function countHtml(d){return fs.readdirSync(d,{withFileTypes:true}).reduce((n,e)=>n+(e.isDirectory()&&!['.git','node_modules'].includes(e.name)?countHtml(path.join(d,e.name)):e.name.endsWith('.html')),0)}
